// Mocks generated by Mockito 5.4.4 from annotations
// in konfio_app_dog/test/data/remote/dog_impl_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:konfio_app_dog/config/api/api.dart' as _i4;
import 'package:konfio_app_dog/config/api/http_maganer.dart' as _i2;
import 'package:konfio_app_dog/shared/utils/json_loader.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpManager_0 extends _i1.SmartFake implements _i2.HttpManager {
  _FakeHttpManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi extends _i1.Mock implements _i4.Api {
  MockApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HttpManager get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeHttpManager_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.HttpManager);

  @override
  _i5.Future<_i3.Response<dynamic>> getApi(
    String? path, {
    dynamic params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApi,
          [path],
          {#params: params},
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #getApi,
            [path],
            {#params: params},
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> postApi(
    String? path,
    dynamic data, [
    _i3.Options? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApi,
          [
            path,
            data,
            options,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #postApi,
            [
              path,
              data,
              options,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> delApi(
    String? path,
    dynamic data, [
    _i3.Options? options,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #delApi,
          [
            path,
            data,
            options,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #delApi,
            [
              path,
              data,
              options,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);

  @override
  _i5.Future<_i3.Response<dynamic>> putApi(
    String? path,
    dynamic data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putApi,
          [
            path,
            data,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #putApi,
            [
              path,
              data,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
}

/// A class which mocks [JsonLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockJsonLoader extends _i1.Mock implements _i6.JsonLoader {
  MockJsonLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<dynamic> cargarDatosJson() => (super.noSuchMethod(
        Invocation.method(
          #cargarDatosJson,
          [],
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<void> guardarDatosJson(
    List<dynamic>? jsonData,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #guardarDatosJson,
          [
            jsonData,
            path,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> verificarCrearYLLenarArchivo(
    List<dynamic>? jsonData,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verificarCrearYLLenarArchivo,
          [
            jsonData,
            path,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<dynamic>> leerDatosDesdeArchivo(String? path) =>
      (super.noSuchMethod(
        Invocation.method(
          #leerDatosDesdeArchivo,
          [path],
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);
}
